#!/bin/bash
# collects all the datfiles produced by "read_scalers"
# and appends run number and fill number to each line

dir="datfiles"
f="acc.dat"

# delete any remaining tmp files
touch $dir/a.tmp
rm $dir/*.tmp

# build fill_time.txt from goodruns.dat
echo "building fill_time.txt..."
awk '{print $1" "$3" "$4}' < goodruns.dat > fill_time.txt



# filter out bad part of F17600 (keep last 14 runs)
mv fill_time.txt fill_time.txt.tmp
echo "filtering bad part of F17600..."
while read line; do
  rrr=$(echo $line | awk '{print $1}')
  fff=$(echo $line | awk '{print $2}')
  ttt=$(echo $line | awk '{print $3}')
  if [ "$fff" -ne "17600" ]; then
    echo $line >> fill_time.txt
  else
    if [ "$rrr" -ge "14160010" ]; then
      echo $line >> fill_time.txt
    fi
  fi
done < fill_time.txt.tmp



echo "building acc file..."
pushd $dir > /dev/null
touch $f
rm $f

# loop over all datfiles
i=0
filli=0
filltmp=0
for file in $(ls run*.dat); do
  runnum=$(echo $file | cut -c4-11)
  fill=$(grep $runnum ../fill_time.txt | awk '{print $2}')
  runtime=$(grep $runnum ../fill_time.txt | awk '{print $3}')

  # check if there's a fill number
  if [ -n "$fill" -a -f ../spinpat/$fill.spin ]; then
    if [ ! -e spin$fill.tmp ]; then
      # obtain spin patterns
      cat ../spinpat/$fill.spin | awk '{print $2" "$3}' > spin$fill.tmp
    fi
    if [ ! -e $file.tmp ]; then
      # add two columns to dat file with spin info
      paste $file spin$fill.tmp > $file.tmp
    fi
    # iterate indices
    let i++
    if [ "$fill" -ne "$filltmp" ]; then
      filltmp=$fill
      let filli++
    fi
    echo "$i $runnum $filli $fill $runtime" 
    # add columns for run index, run #, and fill # and write to acc file
    while read line; do
      echo "$i $runnum $filli $fill $runtime $line" >> $f
    done < $file.tmp
  fi
done
popd > /dev/null

# remove temporary files
rm $dir/*.tmp
#rm fill_time.txt
rm fill_time.txt.tmp

echo "$dir/$f written"

root -b -q 'mk_tree.C("'$dir/$f'")'
