#!/bin/bash
# makes directories and sets up symlinks

mkdir -p log
mkdir -p datfiles
mkdir -p matrix/rootfiles
mkdir -p pdf_bXings_fills
mkdir -p pdf_bXings_runs
mkdir -p pdfs
mkdir -p png_rellum

touch sca2013; rm sca2013
ln -sv /GreyDisk1/sca2013 sca2013

touch spinpat; rm spinpat
ln -sv ../fmstxt/spinpat spinpat
