#!/bin/bash
# reads all scalers in a condor job

f="reader.bat"
outdir="datfiles"
indir="sca2013"

echo "Executable = scaler2_reader_bit.exe" > $f
echo "Universe = vanilla" >> $f
echo "notification = never" >> $f
echo "getenv = True" >> $f
echo "+Experiment = \"star\"" >> $f
echo "+Job_Type = \"cas\"" >> $f
echo  >> $f

mkdir -p log
rm log/*
for file in $(ls $indir); do
  echo "Arguments = $indir/$file" >> $f
  runnum=$(echo $file | cut -c11-18)
  echo "Log = log/run$runnum.log" >> $f
  echo "Output = log/run$runnum.out" >> $f
  echo "Error = log/run$runnum.err" >> $f
  echo "Queue" >> $f
  echo >> $f
done

condor_submit $f
